language: c

before_install:
- sudo apt-get update
- sudo apt-get install -y build-essential autoconf automake libdbus-1-dev libjson-c-dev libxml2-dev libssl-dev zlib1g-dev
- wget https://github.com/warmcat/libwebsockets/archive/v3.0.0.tar.gz
- tar xzf v3.0.0.tar.gz
- cd libwebsockets-3.0.0
- mkdir build
- cd build
- cmake ..
- make
- sudo make install
- cd ..
- cd ..

script:
- cd rpc-broker
- autoreconf --verbose --install --force
- ./configure
- make
- export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
- ./rpc-broker -r 5555 &
- RPCBPID=$!
- dbus-send --system --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames > /tmp/t1
- DBUS_SYSTEM_BUS_ADDRESS=tcp:host=127.0.0.1,port=5555 dbus-send --system --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames > /tmp/t2
- diff -u /tmp/t1 /tmp/t2
- RES=$?
- kill $RPCBPID
- [ $RES -eq 0 ]
