language: c

before_install:
- sudo apt-get update
- sudo apt-get install -y build-essential autoconf automake libdbus-1-dev libjson-c-dev libxml2-dev libssl-dev zlib1g-dev
- wget https://github.com/warmcat/libwebsockets/archive/v3.0.0.tar.gz
- tar xzf v3.0.0.tar.gz
- cd libwebsockets-3.0.0
- mkdir build
- cd build
- cmake ..
- make
- sudo make install
- cd ..
- cd ..

script:
- cd rpc-broker
- autoreconf --verbose --install --force
- ./configure
- make
